# Generated by Django 3.0.3 on 2020-08-31 12:48

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cihai',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('words', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('yin', models.CharField(blank=True, max_length=255, null=True)),
                ('yun', models.CharField(blank=True, max_length=255, null=True)),
                ('key1', models.CharField(blank=True, max_length=255, null=True)),
                ('key2', models.CharField(blank=True, max_length=255, null=True)),
                ('key3', models.CharField(blank=True, max_length=255, null=True)),
                ('key4', models.CharField(blank=True, max_length=255, null=True)),
                ('key5', models.CharField(blank=True, max_length=255, null=True)),
                ('times', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'cihai',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('pron', models.CharField(blank=True, max_length=255, null=True)),
                ('ch', models.CharField(blank=True, max_length=255, null=True)),
                ('key1', models.CharField(blank=True, max_length=255, null=True)),
                ('key2', models.CharField(blank=True, max_length=255, null=True)),
                ('key3', models.CharField(blank=True, max_length=255, null=True)),
                ('key4', models.CharField(blank=True, max_length=255, null=True)),
                ('times', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'words',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
