# Generated by Django 3.0.3 on 2021-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201029_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niceday',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Niceday',
                'managed': True,
            },
        ),
    ]
